#!/usr/bin/env bash
set -e; if [ -n "$DEBUG" ]; then set -x; fi

project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"

for path in "$project_dir"/src/*.ts; do
  file=$(basename "$path")

  if [[ $file == *"spec"* ]]; then
    continue
  fi

  filename=${file%%.*}

  yarn rollup -c --environment entry:"$filename"
done

cp -r "$project_dir"/src/api "$project_dir"/dist/api
