"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccessedStudyguideV1ToJSON = exports.AccessedStudyguideV1FromJSONTyped = exports.AccessedStudyguideV1FromJSON = exports.AccessedStudyguideV1TypeEnum = void 0;
/**
* @export
* @enum {string}
*/
var AccessedStudyguideV1TypeEnum;
(function (AccessedStudyguideV1TypeEnum) {
    AccessedStudyguideV1TypeEnum["OrgOpenstaxEcAccessedStudyguideV1"] = "org.openstax.ec.accessed_studyguide_v1";
})(AccessedStudyguideV1TypeEnum = exports.AccessedStudyguideV1TypeEnum || (exports.AccessedStudyguideV1TypeEnum = {}));
function AccessedStudyguideV1FromJSON(json) {
    return AccessedStudyguideV1FromJSONTyped(json, false);
}
exports.AccessedStudyguideV1FromJSON = AccessedStudyguideV1FromJSON;
function AccessedStudyguideV1FromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'clientClockOccurredAt': (new Date(json['client_clock_occurred_at'])),
        'clientClockSentAt': (new Date(json['client_clock_sent_at'])),
        'type': json['type'],
        'sourceUri': json['source_uri'],
        'sessionUuid': json['session_uuid'],
        'sessionOrder': json['session_order'],
        'pageId': json['page_id'],
        'bookId': json['book_id'],
    };
}
exports.AccessedStudyguideV1FromJSONTyped = AccessedStudyguideV1FromJSONTyped;
function AccessedStudyguideV1ToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'client_clock_occurred_at': (value.clientClockOccurredAt.toISOString()),
        'client_clock_sent_at': (value.clientClockSentAt.toISOString()),
        'type': value.type,
        'source_uri': value.sourceUri,
        'session_uuid': value.sessionUuid,
        'session_order': value.sessionOrder,
        'page_id': value.pageId,
        'book_id': value.bookId,
    };
}
exports.AccessedStudyguideV1ToJSON = AccessedStudyguideV1ToJSON;
