/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AccessedStudyguideV1
 */
export interface AccessedStudyguideV1 {
    /**
     * The RFC 3339 section 5.6 date-time when event actually occurred.
     * @type {Date}
     * @memberof AccessedStudyguideV1
     */
    clientClockOccurredAt: Date;
    /**
     * The RFC 3339 section 5.6 date-time when event was sent to the server.
     * @type {Date}
     * @memberof AccessedStudyguideV1
     */
    clientClockSentAt: Date;
    /**
     * The data's type.
     * @type {string}
     * @memberof AccessedStudyguideV1
     */
    type: AccessedStudyguideV1TypeEnum;
    /**
     * client location when event occurred.
     * @type {string}
     * @memberof AccessedStudyguideV1
     */
    sourceUri: string;
    /**
     * The UUID of the current session, previously generated by the client and submitted in a "session started" event.
     * @type {string}
     * @memberof AccessedStudyguideV1
     */
    sessionUuid: string;
    /**
     * The event's numerical order within this session. E.g. the first event after a session is started should give 0 for this field, the next one should give 1, etc.
     * @type {number}
     * @memberof AccessedStudyguideV1
     */
    sessionOrder: number;
    /**
     * The page id.
     * @type {string}
     * @memberof AccessedStudyguideV1
     */
    pageId: string;
    /**
     * The book id.
     * @type {string}
     * @memberof AccessedStudyguideV1
     */
    bookId: string;
}
/**
* @export
* @enum {string}
*/
export declare enum AccessedStudyguideV1TypeEnum {
    OrgOpenstaxEcAccessedStudyguideV1 = "org.openstax.ec.accessed_studyguide_v1"
}
export declare function AccessedStudyguideV1FromJSON(json: any): AccessedStudyguideV1;
export declare function AccessedStudyguideV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessedStudyguideV1;
export declare function AccessedStudyguideV1ToJSON(value?: AccessedStudyguideV1 | null): any;
