/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ChangedStateV1
 */
export interface ChangedStateV1 {
    /**
     * The RFC 3339 section 5.6 date-time when event actually occurred.
     * @type {Date}
     * @memberof ChangedStateV1
     */
    clientClockOccurredAt: Date;
    /**
     * The RFC 3339 section 5.6 date-time when event was sent to the server.
     * @type {Date}
     * @memberof ChangedStateV1
     */
    clientClockSentAt: Date;
    /**
     * The data's type.
     * @type {string}
     * @memberof ChangedStateV1
     */
    type: ChangedStateV1TypeEnum;
    /**
     * client location when event occurred.
     * @type {string}
     * @memberof ChangedStateV1
     */
    sourceUri: string;
    /**
     * The UUID of the current session, previously generated by the client and submitted in a "session started" event.
     * @type {string}
     * @memberof ChangedStateV1
     */
    sessionUuid: string;
    /**
     * The event's numerical order within this session. E.g. the first event after a session is started should give 0 for this field, the next one should give 1, etc.
     * @type {number}
     * @memberof ChangedStateV1
     */
    sessionOrder: number;
    /**
     * The type of state that is changing, e.g. visibility
     * @type {string}
     * @memberof ChangedStateV1
     */
    stateType: string;
    /**
     * The current value for the state described by :type
     * @type {string}
     * @memberof ChangedStateV1
     */
    current: string;
    /**
     * The previous value for the state described by :type
     * @type {string}
     * @memberof ChangedStateV1
     */
    previous: string;
}
/**
* @export
* @enum {string}
*/
export declare enum ChangedStateV1TypeEnum {
    OrgOpenstaxEcChangedStateV1 = "org.openstax.ec.changed_state_v1"
}
export declare function ChangedStateV1FromJSON(json: any): ChangedStateV1;
export declare function ChangedStateV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangedStateV1;
export declare function ChangedStateV1ToJSON(value?: ChangedStateV1 | null): any;
