"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventsToJSON = exports.EventsFromJSONTyped = exports.EventsFromJSON = void 0;
const runtime_1 = require("../runtime");
const _1 = require("./");
function EventsFromJSON(json) {
    return EventsFromJSONTyped(json, false);
}
exports.EventsFromJSON = EventsFromJSON;
function EventsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'events': !runtime_1.exists(json, 'events') ? undefined : (json['events'].map(_1.EventFromJSON)),
    };
}
exports.EventsFromJSONTyped = EventsFromJSONTyped;
function EventsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'events': value.events === undefined ? undefined : (value.events.map(_1.EventToJSON)),
    };
}
exports.EventsToJSON = EventsToJSON;
