/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Event } from './';
/**
 *
 * @export
 * @interface Events
 */
export interface Events {
    /**
     * Array of Event
     * @type {Array<Event>}
     * @memberof Events
     */
    events?: Array<Event>;
}
export declare function EventsFromJSON(json: any): Events;
export declare function EventsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Events;
export declare function EventsToJSON(value?: Events | null): any;
