"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InfoDataToJSON = exports.InfoDataFromJSONTyped = exports.InfoDataFromJSON = void 0;
const runtime_1 = require("../runtime");
function InfoDataFromJSON(json) {
    return InfoDataFromJSONTyped(json, false);
}
exports.InfoDataFromJSON = InfoDataFromJSON;
function InfoDataFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'kafkaTopics': !runtime_1.exists(json, 'kafka_topics') ? undefined : json['kafka_topics'],
        'schemaRegistrySubjects': !runtime_1.exists(json, 'schema_registry_subjects') ? undefined : json['schema_registry_subjects'],
    };
}
exports.InfoDataFromJSONTyped = InfoDataFromJSONTyped;
function InfoDataToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'kafka_topics': value.kafkaTopics,
        'schema_registry_subjects': value.schemaRegistrySubjects,
    };
}
exports.InfoDataToJSON = InfoDataToJSON;
