"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InfoResultsToJSON = exports.InfoResultsFromJSONTyped = exports.InfoResultsFromJSON = void 0;
const runtime_1 = require("../runtime");
const _1 = require("./");
function InfoResultsFromJSON(json) {
    return InfoResultsFromJSONTyped(json, false);
}
exports.InfoResultsFromJSON = InfoResultsFromJSON;
function InfoResultsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'overallTookMs': !runtime_1.exists(json, 'overall_took_ms') ? undefined : json['overall_took_ms'],
        'envName': !runtime_1.exists(json, 'env_name') ? undefined : json['env_name'],
        'accountsEnvName': !runtime_1.exists(json, 'accounts_env_name') ? undefined : json['accounts_env_name'],
        'amiId': !runtime_1.exists(json, 'ami_id') ? undefined : json['ami_id'],
        'gitSha': !runtime_1.exists(json, 'git_sha') ? undefined : json['git_sha'],
        'data': !runtime_1.exists(json, 'data') ? undefined : _1.InfoDataFromJSON(json['data']),
    };
}
exports.InfoResultsFromJSONTyped = InfoResultsFromJSONTyped;
function InfoResultsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'data': _1.InfoDataToJSON(value.data),
    };
}
exports.InfoResultsToJSON = InfoResultsToJSON;
