/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface NudgedV1
 */
export interface NudgedV1 {
    /**
     * The RFC 3339 section 5.6 date-time when event actually occurred.
     * @type {Date}
     * @memberof NudgedV1
     */
    clientClockOccurredAt: Date;
    /**
     * The RFC 3339 section 5.6 date-time when event was sent to the server.
     * @type {Date}
     * @memberof NudgedV1
     */
    clientClockSentAt: Date;
    /**
     * The data's type.
     * @type {string}
     * @memberof NudgedV1
     */
    type: NudgedV1TypeEnum;
    /**
     * client location when event occurred.
     * @type {string}
     * @memberof NudgedV1
     */
    sourceUri: string;
    /**
     * The UUID of the current session, previously generated by the client and submitted in a "session started" event.
     * @type {string}
     * @memberof NudgedV1
     */
    sessionUuid: string;
    /**
     * The event's numerical order within this session. E.g. the first event after a session is started should give 0 for this field, the next one should give 1, etc.
     * @type {number}
     * @memberof NudgedV1
     */
    sessionOrder: number;
    /**
     * The app sourcing the nudge (e.g., tutor.
     * @type {string}
     * @memberof NudgedV1
     */
    app: string;
    /**
     * The target of the nudge (e.g., study_guides).
     * @type {string}
     * @memberof NudgedV1
     */
    target: string;
    /**
     * The nudge context (e.g., a book uuid).
     * @type {string}
     * @memberof NudgedV1
     */
    context: string;
    /**
     * The nudge flavor (e.g., full screen v2).
     * @type {string}
     * @memberof NudgedV1
     */
    flavor: string;
    /**
     * The nudge medium (e.g., email).
     * @type {string}
     * @memberof NudgedV1
     */
    medium: string;
}
/**
* @export
* @enum {string}
*/
export declare enum NudgedV1TypeEnum {
    OrgOpenstaxEcNudgedV1 = "org.openstax.ec.nudged_v1"
}
export declare function NudgedV1FromJSON(json: any): NudgedV1;
export declare function NudgedV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): NudgedV1;
export declare function NudgedV1ToJSON(value?: NudgedV1 | null): any;
