"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NudgedV1ToJSON = exports.NudgedV1FromJSONTyped = exports.NudgedV1FromJSON = exports.NudgedV1TypeEnum = void 0;
/**
* @export
* @enum {string}
*/
var NudgedV1TypeEnum;
(function (NudgedV1TypeEnum) {
    NudgedV1TypeEnum["OrgOpenstaxEcNudgedV1"] = "org.openstax.ec.nudged_v1";
})(NudgedV1TypeEnum = exports.NudgedV1TypeEnum || (exports.NudgedV1TypeEnum = {}));
function NudgedV1FromJSON(json) {
    return NudgedV1FromJSONTyped(json, false);
}
exports.NudgedV1FromJSON = NudgedV1FromJSON;
function NudgedV1FromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'clientClockOccurredAt': (new Date(json['client_clock_occurred_at'])),
        'clientClockSentAt': (new Date(json['client_clock_sent_at'])),
        'type': json['type'],
        'sourceUri': json['source_uri'],
        'sessionUuid': json['session_uuid'],
        'sessionOrder': json['session_order'],
        'app': json['app'],
        'target': json['target'],
        'context': json['context'],
        'flavor': json['flavor'],
        'medium': json['medium'],
    };
}
exports.NudgedV1FromJSONTyped = NudgedV1FromJSONTyped;
function NudgedV1ToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'client_clock_occurred_at': (value.clientClockOccurredAt.toISOString()),
        'client_clock_sent_at': (value.clientClockSentAt.toISOString()),
        'type': value.type,
        'source_uri': value.sourceUri,
        'session_uuid': value.sessionUuid,
        'session_order': value.sessionOrder,
        'app': value.app,
        'target': value.target,
        'context': value.context,
        'flavor': value.flavor,
        'medium': value.medium,
    };
}
exports.NudgedV1ToJSON = NudgedV1ToJSON;
