/**
 * OpenStax Event Capture API
 * The Event Capture API for OpenStax.  Requests to this API should include `application/json` in the `Accept` header.  The desired API version is specified in the request URL, e.g. `[domain]/api/v0`. While the API does support a default version, that version will change over time and therefore should not be used in production code!
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface StartedSessionV1
 */
export interface StartedSessionV1 {
    /**
     * The RFC 3339 section 5.6 date-time when event actually occurred.
     * @type {Date}
     * @memberof StartedSessionV1
     */
    clientClockOccurredAt: Date;
    /**
     * The RFC 3339 section 5.6 date-time when event was sent to the server.
     * @type {Date}
     * @memberof StartedSessionV1
     */
    clientClockSentAt: Date;
    /**
     * The data's type.
     * @type {string}
     * @memberof StartedSessionV1
     */
    type: StartedSessionV1TypeEnum;
    /**
     * client location when event occurred.
     * @type {string}
     * @memberof StartedSessionV1
     */
    sourceUri: string;
    /**
     * The referrer.
     * @type {string}
     * @memberof StartedSessionV1
     */
    referrer: string;
    /**
     * The client generates this UUID and references it for all future events in this session.
     * @type {string}
     * @memberof StartedSessionV1
     */
    sessionUuid: string;
    /**
     * The code version of the app.
     * @type {string}
     * @memberof StartedSessionV1
     */
    releaseId?: string;
    /**
     * The service worker state
     * @type {string}
     * @memberof StartedSessionV1
     */
    serviceWorker?: StartedSessionV1ServiceWorkerEnum;
}
/**
* @export
* @enum {string}
*/
export declare enum StartedSessionV1TypeEnum {
    OrgOpenstaxEcStartedSessionV1 = "org.openstax.ec.started_session_v1"
} /**
* @export
* @enum {string}
*/
export declare enum StartedSessionV1ServiceWorkerEnum {
    Unsupported = "unsupported",
    Inactive = "inactive",
    Active = "active"
}
export declare function StartedSessionV1FromJSON(json: any): StartedSessionV1;
export declare function StartedSessionV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): StartedSessionV1;
export declare function StartedSessionV1ToJSON(value?: StartedSessionV1 | null): any;
